apiVersion: v1
kind: Service
metadata:
  name: demo-canary
  namespace: demo-canary
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: demo-canary
