apiVersion: v1
kind: Service
metadata:
  name: demo-blue-green
  namespace: demo-blue-green
  labels:
    app: demo-blue-green
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: demo-blue-green
